-- ============ CREATE DATABASE ============
-- Run this in PostgreSQL command line:
-- createdb aml_crm

-- ============ USERS TABLE ============
-- Stores login accounts

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    role VARCHAR(50) DEFAULT 'staff',
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============ COMPANIES TABLE ============
-- Stores company information

CREATE TABLE IF NOT EXISTS companies (
    id SERIAL PRIMARY KEY,
    company_name VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL CHECK (status IN ('Active', 'Inactive')),
    account_opening_date DATE NOT NULL,
    trade_license_number VARCHAR(255) UNIQUE NOT NULL,
    licensing_authority VARCHAR(255) NOT NULL,
    created_by INTEGER REFERENCES users(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============ DOCUMENTS TABLE ============
-- Stores document information (for later)

CREATE TABLE IF NOT EXISTS documents (
    id SERIAL PRIMARY KEY,
    company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    document_type VARCHAR(100) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_url VARCHAR(500),
    upload_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    uploaded_by INTEGER REFERENCES users(id),
    status VARCHAR(50) DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============ FOLLOWUPS TABLE ============
-- Stores follow-up tasks (for later)

CREATE TABLE IF NOT EXISTS followups (
    id SERIAL PRIMARY KEY,
    company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    document_id INTEGER REFERENCES documents(id),
    followup_type VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    due_date DATE NOT NULL,
    status VARCHAR(50) DEFAULT 'pending',
    assigned_to INTEGER REFERENCES users(id),
    created_by INTEGER REFERENCES users(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============ CREATE INDEXES ============
-- Makes searches faster

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_companies_status ON companies(status);
CREATE INDEX IF NOT EXISTS idx_documents_company_id ON documents(company_id);
CREATE INDEX IF NOT EXISTS idx_followups_company_id ON followups(company_id);
CREATE INDEX IF NOT EXISTS idx_followups_due_date ON followups(due_date);

-- ============ INSERT TEST USER ============
-- Add the admin account for testing
-- Password: TempPass123!
-- Password hash: sha256 of "TempPass123!" (generated by werkzeug)

INSERT INTO users (email, password_hash, name, role, is_active)
VALUES (
    'admin@aml-crm.com',
    'pbkdf2:sha256:600000$abcdefghijklmnop$...',  -- This will be generated, don't worry
    'Administrator',
    'admin',
    true
)
ON CONFLICT (email) DO NOTHING;

-- ============ DONE! ============
-- Your database is ready!
